name = "Cobblemon - S2"
author = "AmeMeida"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48966825e4231fb00e830a8692d8213df50decbd036547bd3c1f39f3bbaa65bc"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
