name = "Cobblemon - S2"
author = "AmeMeida"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64b20a4e5c975ffd6b0309b997366c36cfd2628a1eb2e69f17048d4462e47555"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
