name = "Cobblemon - S2"
author = "AmeMeida"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5578db1df751d95a14edbcef00225961aa18f273aa4f203de0ed1c263393e1f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
